"""KeychainOS theme: Glassy Blur."""

NAME = "glassy_blur"
DISPLAY_NAME = "Glassy Blur"
BACKGROUND = 0x1AF6
STATUS_BACKGROUND = 0x1272
STATUS_TEXT = 0xFFFF
TITLE_TEXT = 0xFFFF
PRIMARY_TEXT = 0xFFFF
SECONDARY_TEXT = 0xBDF7
LABEL_TEXT = 0xFFFF
INSTRUCTION_TEXT = 0xFFFF
TILE_TOP = 0x6D9F
TILE_BOTTOM = 0x1B54
TILE_BORDER = 0xDFFF
TILE_SHADOW = 0x0010
TILE_GLOSS = 0xEFFF
PEEK_TILE = 0x3CDA
DOT_ACTIVE = 0xFFFF
DOT_INACTIVE = 0x9CF3
BATTERY_BORDER = 0xFFFF
BATTERY_FILL = 0x07FF
FILES_TOP = 0x7FFF
FILES_BOTTOM = 0x05B5
GAMES_TOP = 0xA69F
GAMES_BOTTOM = 0x401F
NOTES_TOP = 0xFF1F
NOTES_BOTTOM = 0xA81F
SETTINGS_TOP = 0xCFFF
SETTINGS_BOTTOM = 0x3C5F
SNAKE_TOP = 0x87F0
SNAKE_BOTTOM = 0x03A0
TICTACTOE_TOP = 0x7DFF
TICTACTOE_BOTTOM = 0x03BF
TILE_SIZE = 132
TILE_X = 54
TILE_Y = 78
PEEK_WIDTH = 22
LABEL_Y = 228
DOT_Y = 268
INSTRUCTION_Y = 288
ACTION_Y = 304
SHOW_GLOSS = True
SHOW_SHADOW = True
PIXEL_STYLE = False
COMPACT_LAYOUT = False
ROUNDED_STEPS = 8


def app_colours(name):
    mapping = {
        "FILES": (FILES_TOP, FILES_BOTTOM),
        "GAMES": (GAMES_TOP, GAMES_BOTTOM),
        "NOTES": (NOTES_TOP, NOTES_BOTTOM),
        "SETTINGS": (SETTINGS_TOP, SETTINGS_BOTTOM),
        "SNAKE": (SNAKE_TOP, SNAKE_BOTTOM),
        "TIC TAC TOE": (TICTACTOE_TOP, TICTACTOE_BOTTOM),
    }
    return mapping.get(name, (TILE_TOP, TILE_BOTTOM))
