"""KeychainOS theme: Pastel Rounded."""

NAME = "pastel_rounded"
DISPLAY_NAME = "Pastel Rounded"
BACKGROUND = 0xF5DB
STATUS_BACKGROUND = 0xF5DB
STATUS_TEXT = 0x2104
TITLE_TEXT = 0x801F
PRIMARY_TEXT = 0xFFFF
SECONDARY_TEXT = 0x8410
LABEL_TEXT = 0xFFFF
INSTRUCTION_TEXT = 0x801F
TILE_TOP = 0xB65F
TILE_BOTTOM = 0x7B5F
TILE_BORDER = 0xFFFF
TILE_SHADOW = 0xDEFB
TILE_GLOSS = 0xFFFF
PEEK_TILE = 0xEF7D
DOT_ACTIVE = 0x801F
DOT_INACTIVE = 0xDEFB
BATTERY_BORDER = 0x2104
BATTERY_FILL = 0x801F
FILES_TOP = 0x7FFF
FILES_BOTTOM = 0x3D99
GAMES_TOP = 0xB65F
GAMES_BOTTOM = 0x801F
NOTES_TOP = 0x9D7F
NOTES_BOTTOM = 0x635F
SETTINGS_TOP = 0xFAD7
SETTINGS_BOTTOM = 0xF81F
SNAKE_TOP = 0x87F0
SNAKE_BOTTOM = 0x45A8
TICTACTOE_TOP = 0xA69F
TICTACTOE_BOTTOM = 0x635F
TILE_SIZE = 132
TILE_X = 54
TILE_Y = 78
PEEK_WIDTH = 22
LABEL_Y = 228
DOT_Y = 268
INSTRUCTION_Y = 288
ACTION_Y = 304
SHOW_GLOSS = True
SHOW_SHADOW = True
PIXEL_STYLE = False
COMPACT_LAYOUT = False
ROUNDED_STEPS = 12


def app_colours(name):
    mapping = {
        "FILES": (FILES_TOP, FILES_BOTTOM),
        "GAMES": (GAMES_TOP, GAMES_BOTTOM),
        "NOTES": (NOTES_TOP, NOTES_BOTTOM),
        "SETTINGS": (SETTINGS_TOP, SETTINGS_BOTTOM),
        "SNAKE": (SNAKE_TOP, SNAKE_BOTTOM),
        "TIC TAC TOE": (TICTACTOE_TOP, TICTACTOE_BOTTOM),
    }
    return mapping.get(name, (TILE_TOP, TILE_BOTTOM))
