"""KeychainOS theme: Compact Clean."""

NAME = "compact_clean"
DISPLAY_NAME = "Compact Clean"
BACKGROUND = 0xF7BE
STATUS_BACKGROUND = 0xF7BE
STATUS_TEXT = 0x0000
TITLE_TEXT = 0x001F
PRIMARY_TEXT = 0xFFFF
SECONDARY_TEXT = 0x4208
LABEL_TEXT = 0xFFFF
INSTRUCTION_TEXT = 0x001F
TILE_TOP = 0x2D7F
TILE_BOTTOM = 0x021F
TILE_BORDER = 0xFFFF
TILE_SHADOW = 0xC618
TILE_GLOSS = 0xBFFF
PEEK_TILE = 0xE71C
DOT_ACTIVE = 0x021F
DOT_INACTIVE = 0xC618
BATTERY_BORDER = 0x0000
BATTERY_FILL = 0x0000
FILES_TOP = 0xFFE0
FILES_BOTTOM = 0xFD20
GAMES_TOP = 0x2D7F
GAMES_BOTTOM = 0x021F
NOTES_TOP = 0xB65F
NOTES_BOTTOM = 0x801F
SETTINGS_TOP = 0x5D7F
SETTINGS_BOTTOM = 0x021F
SNAKE_TOP = 0x07E0
SNAKE_BOTTOM = 0x0320
TICTACTOE_TOP = 0x07FF
TICTACTOE_BOTTOM = 0x001F
TILE_SIZE = 116
TILE_X = 62
TILE_Y = 86
PEEK_WIDTH = 20
LABEL_Y = 220
DOT_Y = 258
INSTRUCTION_Y = 282
ACTION_Y = 300
SHOW_GLOSS = True
SHOW_SHADOW = True
PIXEL_STYLE = False
COMPACT_LAYOUT = True
ROUNDED_STEPS = 8


def app_colours(name):
    mapping = {
        "FILES": (FILES_TOP, FILES_BOTTOM),
        "GAMES": (GAMES_TOP, GAMES_BOTTOM),
        "NOTES": (NOTES_TOP, NOTES_BOTTOM),
        "SETTINGS": (SETTINGS_TOP, SETTINGS_BOTTOM),
        "SNAKE": (SNAKE_TOP, SNAKE_BOTTOM),
        "TIC TAC TOE": (TICTACTOE_TOP, TICTACTOE_BOTTOM),
    }
    return mapping.get(name, (TILE_TOP, TILE_BOTTOM))
